version: '3.8'
services:
  backend:
    build:
      context: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000

  frontend:
    build:
      context: ./example-frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
