version: '3.8'

services:
  backend:
    build: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    restart: unless-stopped

  frontend:
    build: ./example-frontend
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

networks:
    external:
      name: backend-frontend
